MeetRoomConfig:
    type: object
    properties:
        chat:
            $ref: '#/MeetChatConfig'
            description: Config for the chat feature in the room.
        recording:
            $ref: '#/MeetRecordingConfig'
            description: Config for recording the room.
        virtualBackground:
            $ref: '#/MeetVirtualBackgroundConfig'
            description: Config for virtual background in the room.
        e2ee:
            $ref: '#/MeetE2EEConfig'
            description: Config for End-to-End Encryption (E2EE) in the room.
MeetChatConfig:
    type: object
    properties:
        enabled:
            type: boolean
            default: true
            example: true
            description: If true, the room will be allowed to send and receive chat messages.
MeetRecordingConfig:
    type: object
    properties:
        enabled:
            type: boolean
            default: true
            example: true
            description: If true, the room will be allowed to record the video of the participants.
        layout:
            type: string
            enum:
                - grid
                - speaker
                - single-speaker
                # - grid-light
                # - speaker-light
                # - single-speaker-light
            default: grid
            example: grid
            description: |
                Defines the layout of the recording. Options are:
                - `grid`: All participants are shown in a grid layout.
                - `speaker`: The active speaker is shown prominently, with other participants in smaller thumbnails.
                - `single-speaker`: Only the active speaker is shown in the recording.
              # - `grid-light`: Similar to `grid` but with a light-themed background.
              # - `speaker-light`: Similar to `speaker` but with a light-themed background.
              # - `single-speaker-light`: Similar to `single-speaker` but with a light-themed background.
        allowAccessTo:
            type: string
            enum:
                - admin
                - admin_moderator
                - admin_moderator_speaker
            default: admin_moderator_speaker
            example: admin_moderator_speaker
            description: |
                Defines who can access the recording. Options are:
                - `admin`: Only administrators can access the recording.
                - `admin_moderator`: Administrators and moderators can access the recording.
                - `admin_moderator_speaker`: Administrators, moderators and speakers can access the recording.
MeetVirtualBackgroundConfig:
    type: object
    properties:
        enabled:
            type: boolean
            default: true
            example: true
            description: If true, the room will be allowed to use virtual background.
MeetE2EEConfig:
    type: object
    properties:
        enabled:
            type: boolean
            default: false
            example: false
            description: >
                If true, the room will have End-to-End Encryption (E2EE) enabled.<br/>
                This ensures that the media streams are encrypted from the sender to the receiver, providing enhanced privacy and security for the participants.<br/>
                **Enabling E2EE will disable the recording feature for the room**.
