services:
  meet-demo:
    image: openvidu/openvidu-meet-demo:3.4.1
    container_name: meet-demo
    environment:
      - SERVER_PORT=6080
      - OV_MEET_SERVER_URL=${OV_MEET_SERVER_URL:-https://meet-demo.openvidu.io}
      - OV_MEET_API_KEY=${OV_MEET_API_KEY:-meet-api-key}
    restart: unless-stopped

  caddy:
    image: cruizba/autohttps:v1.0.0
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
    environment:
      - SERVICES=meet-demo:6080=${DOMAIN:?mandatory}
    restart: unless-stopped
    depends_on:
      - meet-demo

volumes:
  caddy_data:
