apiKeyHeader:
    type: apiKey
    name: X-API-KEY
    in: header
    description: >
        The API key to authenticate the request. This key is required to access the OpenVidu Meet API.
accessTokenHeader:
    type: apiKey
    name: Authorization
    in: header
    description: >
        The JWT token to authenticate the request in case of consuming the API from the OpenVidu Meet frontend.
refreshTokenHeader:
    type: apiKey
    name: X-Refresh-Token
    in: header
    description: >
        The JWT token to refresh the access token when it expires.
roomMemberTokenHeader:
    type: apiKey
    name: X-Room-Member-Token
    in: header
    description: >
        The JWT token to authenticate a room member when accessing room and its resources.
